# Generated by Django 5.1.7 on 2026-01-28 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название бота')),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('whatsapp', 'WhatsApp'), ('vk', 'VK'), ('instagram', 'Instagram')], max_length=20, verbose_name='Платформа')),
                ('bot_token', models.CharField(blank=True, max_length=500, verbose_name='Токен бота')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('inactive', 'Неактивен'), ('paused', 'Приостановлен')], default='inactive', max_length=20, verbose_name='Статус')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='bot_avatars/', verbose_name='Аватар')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('total_conversations', models.IntegerField(default=0, verbose_name='Всего диалогов')),
                ('total_messages', models.IntegerField(default=0, verbose_name='Всего сообщений')),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Конверсия %')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Бот',
                'verbose_name_plural': 'Боты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=200, verbose_name='ID пользователя')),
                ('user_name', models.CharField(blank=True, max_length=200, verbose_name='Имя пользователя')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начат')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='Последнее сообщение')),
                ('is_lead', models.BooleanField(default=False, verbose_name='Является лидом')),
                ('lead_email', models.EmailField(blank=True, max_length=254, verbose_name='Email лида')),
                ('lead_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон лида')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.botagent')),
            ],
            options={
                'verbose_name': 'Диалог',
                'verbose_name_plural': 'Диалоги',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='knowledge_base/', verbose_name='Файл')),
                ('file_type', models.CharField(max_length=10, verbose_name='Тип файла')),
                ('content_extracted', models.TextField(blank=True, verbose_name='Извлеченный текст')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='core.botagent')),
            ],
            options={
                'verbose_name': 'Документ базы знаний',
                'verbose_name_plural': 'База знаний',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('bot', 'Бот'), ('system', 'Система')], max_length=10, verbose_name='Роль')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.conversation')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('new_conversations', models.IntegerField(default=0, verbose_name='Новых диалогов')),
                ('messages_sent', models.IntegerField(default=0, verbose_name='Отправлено сообщений')),
                ('leads_captured', models.IntegerField(default=0, verbose_name='Захвачено лидов')),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='core.botagent')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
                'ordering': ['-date'],
                'unique_together': {('bot', 'date')},
            },
        ),
    ]
