# Generated by Django 5.1.7 on 2026-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='botagent',
            name='api_hash',
            field=models.CharField(blank=True, max_length=100, verbose_name='API Hash'),
        ),
        migrations.AddField(
            model_name='botagent',
            name='api_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='API ID'),
        ),
        migrations.AddField(
            model_name='botagent',
            name='phone_code_hash',
            field=models.CharField(blank=True, max_length=500, verbose_name='Хеш кода'),
        ),
        migrations.AddField(
            model_name='botagent',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='botagent',
            name='session_string',
            field=models.TextField(blank=True, verbose_name='Session String'),
        ),
        migrations.AddField(
            model_name='botagent',
            name='system_prompt',
            field=models.TextField(blank=True, default='Ты - профессиональный sales-ассистент.', verbose_name='Системный промпт'),
        ),
        migrations.AlterField(
            model_name='botagent',
            name='status',
            field=models.CharField(choices=[('waiting_code', 'Ожидание кода'), ('active', 'Активен'), ('inactive', 'Неактивен'), ('paused', 'Приостановлен'), ('invalid', 'Ошибка авторизации')], default='inactive', max_length=20, verbose_name='Статус'),
        ),
    ]
