# Generated by Django 5.2.9 on 2026-02-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_botagent_api_hash_botagent_api_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botagent',
            name='api_id',
            field=models.IntegerField(blank=True, verbose_name='API ID'),
        ),
    ]
