# Generated by Django 5.2.9 on 2026-02-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_botagent_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botagent',
            name='api_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='API ID'),
        ),
    ]
