# Generated by Django 5.2.9 on 2026-02-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_botagent_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botagent',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='API ID'),
        ),
    ]
