# Generated by Django 5.2.9 on 2026-02-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_botagent_api_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botagent',
            name='session_string',
            field=models.TextField(blank=True, null=True, verbose_name='Session String'),
        ),
    ]
