# Generated by Django 5.2.9 on 2026-02-03 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_botagent_session_string'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='file_size',
            field=models.BigIntegerField(default=0, verbose_name='Размер файла (байт)'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='core.botagent'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(upload_to='knowledge_base/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='knowledgebase',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('doc', 'Word (DOC)'), ('docx', 'Word (DOCX)'), ('txt', 'Text'), ('csv', 'CSV'), ('xlsx', 'Excel (XLSX)'), ('xls', 'Excel (XLS)'), ('json', 'JSON'), ('md', 'Markdown'), ('other', 'Другой')], max_length=10, verbose_name='Тип файла'),
        ),
    ]
