# Generated by Django 5.2.9 on 2026-02-03 17:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_knowledgebase_description_knowledgebase_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebase',
            name='file',
            field=models.FileField(upload_to=core.models.knowledge_base_upload_path, verbose_name='Файл'),
        ),
    ]
