# Generated by Django 5.2.9 on 2026-02-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_knowledgebase_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_type', models.CharField(choices=[('bitrix24', 'Bitrix24'), ('amocrm', 'AmoCRM')], max_length=20, verbose_name='Тип CRM')),
                ('status', models.CharField(choices=[('disconnected', 'Отключено'), ('connecting', 'Подключение...'), ('connected', 'Подключено'), ('error', 'Ошибка')], default='disconnected', max_length=20, verbose_name='Статус')),
                ('domain', models.CharField(blank=True, max_length=255, verbose_name='Домен/URL')),
                ('access_token', models.TextField(blank=True, verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Срок действия токена')),
                ('webhook_url', models.CharField(blank=True, max_length=500, verbose_name='Webhook URL')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('settings', models.JSONField(blank=True, default=dict, verbose_name='Настройки')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('leads_synced', models.IntegerField(default=0, verbose_name='Синхронизировано лидов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRM Интеграция',
                'verbose_name_plural': 'CRM Интеграции',
                'unique_together': {('user', 'crm_type')},
            },
        ),
        migrations.CreateModel(
            name='CRMSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_lead', 'Создание лида'), ('update_lead', 'Обновление лида'), ('create_contact', 'Создание контакта'), ('sync_all', 'Полная синхронизация')], max_length=50, verbose_name='Действие')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('error', 'Ошибка'), ('pending', 'В процессе')], default='pending', max_length=20, verbose_name='Статус')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='Ответ')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='core.crmintegration')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизации',
                'ordering': ['-created_at'],
            },
        ),
    ]
