# Generated by Django 5.2.9 on 2026-02-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_crmintegration_crmsynclog'),
    ]

    operations = [
        migrations.AddField(
            model_name='crmintegration',
            name='credentials_json',
            field=models.TextField(blank=True, verbose_name='Google Credentials JSON'),
        ),
        migrations.AddField(
            model_name='crmintegration',
            name='sheet_name',
            field=models.CharField(blank=True, default='Sheet1', max_length=100, verbose_name='Название листа'),
        ),
        migrations.AddField(
            model_name='crmintegration',
            name='spreadsheet_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='ID таблицы'),
        ),
        migrations.AlterField(
            model_name='crmintegration',
            name='crm_type',
            field=models.CharField(choices=[('bitrix24', 'Bitrix24'), ('amocrm', 'AmoCRM'), ('moysklad', 'МойСклад'), ('google_sheets', 'Google Sheets')], max_length=20, verbose_name='Тип CRM'),
        ),
        migrations.AlterField(
            model_name='crmsynclog',
            name='action',
            field=models.CharField(choices=[('create_lead', 'Создание лида'), ('update_lead', 'Обновление лида'), ('create_contact', 'Создание контакта'), ('create_order', 'Создание заказа'), ('sync_products', 'Синхронизация товаров'), ('append_row', 'Добавление строки'), ('sync_all', 'Полная синхронизация')], max_length=50, verbose_name='Действие'),
        ),
    ]
